### ISSUE TITLE
Eventually logging multiple occurances of the same exception

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#102]
Eventually doesn't always recognize multiple occurrences of exceptions as being the same:
```
DeliveryError: Marcel tried to Eventually see if side nav expanded is equal to <True> 37 times over 10 seconds, but got:
    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>

    AssertionError: 
Expected: <True>
     but: was <False>
```
